CREATE TABLE Release (
    release_id UUID PRIMARY KEY,
    version VARCHAR(255) NOT NULL,
    release_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changelog TEXT,
    release_type VARCHAR(255) NOT NULL DEFAULT 'PRODUCTION',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (release_id) REFERENCES Product(product_id) ON DELETE CASCADE
)

